### ISSUE TITLE
How to make fluid gestures work after installing module?

### ISSUE THREAD

**Issue by e-t-l** [f1j4r/Magisk-DisableNavBar#1]
After flashing this module and rebooting, it successfully removed the system navigation gestures, but it did not replace them with the intended app (in my case, it should be Fluid NG). I can see that there is a "Fluid.apk" file in the module directory tree, but when I run 
`pm install /data/adb/modules/fluid/system/priv-app/Fluid/Fluid.apk`
the result is: 
`Failure [INSTALL_FAILED_SESSION_INVALID: System updates from unknown sources are blocked]`
Checking system apps, Fluid NG does not appear to be installed at all.

Am I supposed to install Fluid NG separately from an app store?

**Comment by e-t-l** [comment]
update: When I went to install the app from Aurora Store, it showed as already installed. When I tapped the "open" button, however, it just triggered a crash dialog. 

So apparently the Fluid NG app *is* installed, but it cannot be launched. Right now, gestures *are not working*. Is there a step I'm supposed to perform in order to make Fluid gestures work or to configure them?

**Comment by f1j4r** [comment]
Sorry this module only works on Android 11 below. if you want to install this module and the app separately you can delete "priv-app" folder inside archive and rezip it and install the module. if it still doesn't work delete all folder inside "/system/" so this module will only disable system navigation and you can try another app. make sure you install the app first before installing the module.
